### ISSUE TITLE
VCS todo list

### ISSUE THREAD

**Issue by ghost** [UV-CDAT/uvcdat-docs#5]
- [ ] TESTING, everywhere!!! 
- [ ] Find and submit issues on deprecations in all vcs modules 
    - [ ] Canvas.py                                 
    - [ ] Pboxeslines.py                            
    - [ ] Pdata.py                                  
    - [ ] Pformat.py                                
    - [ ] Plegend.py                                
    - [ ] Ptext.py                                  
    - [ ] Pxlabels.py                               
    - [ ] Pxtickmarks.py                            
    - [ ] Pylabels.py                
    - [ ] Pytickmarks.py            
    - [ ] VCS_validation_functions  
    - [ ] VTKAnimate.py             
    - [ ] VTKPlots.py               
    - [ ] __init__.py               
    - [ ] animate_helper.py         
    - [ ] boxfill.py 
    - [ ] colormap.py    
    - [ ] colorpicker.py 
    - [ ] colors.py      
    - [ ] configurator.py
    - [ ] displayplot.py 
    - [ ] dv3d.py        
    - [ ] error.py       
    - [ ] fillarea.py
    - [ ] install_vcs.py              
    - [ ] isofill.py                  
    - [ ] isoline.py                      
    - [ ] line.py                       
    - [ ] manageElements.py             
    - [ ] marker.py                      
    - [ ] meshfill.py                   
    - [ ] pauser.py                                           
    - [ ] png.py               
    - [ ] projection.py            
    - [ ] queries.py               
    - [ ] taylor.py                
    - [ ] template.py              
    - [ ] testtemplate.py          
    - [ ] textcombined.py          
    - [ ] textorientation.py
    - [ ] texttable.py
    - [ ] unified1D.py
    - [ ] utils.py
    - [ ] vcs2vtk.py
    - [ ] vcshelp.py
    - [ ] vector.py
    - [ ] xmldocs.py
- [ ] Fix pdf output
  - [ ] doctest/code-block directives run out of space. 80 character maximum on those.
- [x] Convert all Examples to doctests.
  - [x] Canvas.py
  - [x] xmldocs.py
  - [x] manageElements.py
  - [x] animate_helper.py
  - [x] boxfill.py
  - [x] texttable.py
  - [x] colors.py
  - [x] colormap.py
  - [x] template.py
  - [x] colorpicker.py
  - [x] pauser.py
  - [x] fillarea.py
  - [x] unified1D.py
  - [x] projection.py
  - [x] Pxlabels.py
  - [x] displayplot.py
  - [x] queries.py
  - [x] textorientation.py
  - [x] textcombined.py
  - [x] utils.py
  - [x] vcshelp.py
  - [x] Pylabels.py
  - [x] Pdata.py
  - [x] isofill.py
  - [x] Pytickmarks.py
  - [x] Pxtickmarks.py
  - [x] taylor.py
  - [x] xmldocs.py
  - [x] vector.py
  - [x] dv3d.py
  - [x] marker.py
  - [x] meshfill.py
  - [x] Ptext.py
  - [x] testtemplate.py
  - [x] Pboxeslines.py
  - [x] isoline.py
  - [x] Pformat.py
  - [x] line.py
  - [x] Plegend.py
- [x] Update xmldocs to use docstring generation function(s) instead of hardcoding dict entries.
- [x] Run doctests and note what fails and why below:
  - [x] General errors
    - [x] script examples complain about overwriting existing file (add more to doctest cleanup)
  - [ ] Canvas.py
    - [x] grid() doesn't exist (is this supposed to be cmor's grid function?)
    - [x] getplot() deprecated
    - [x] textcombined() assumes args non-empty
    - [ ] gif not implemented
    - [x] incorrectly calling drawtextcombined
  - [ ] xmldocs.py
  - [ ] manageElements.py
    - [ ] get() 
      - [x] can't plot a colormap
      - [x] line 'red' doesn't exist (may be deleting it in cleanup)
      - [ ] taylordiagram has errors when plotting clt.nc['u']
  - [x] animate_helper.py
    - [x] 'array' not defined
    - [x] VTKAnimate not callable
  - [ ] textcombined.py
    - [ ] texttable object already exists (possible alias conflict)
- [ ] Add top-level module descriptions    
  - [ ] Canvas.py
  - [ ] manageElements.py
  - [ ] animate_helper.py
  - [ ] boxfill.py
  - [ ] texttable.py
  - [ ] colors.py
  - [ ] colormap.py
  - [ ] template.py
  - [ ] colorpicker.py
  - [ ] fillarea.py
  - [ ] unified1D.py
  - [ ] projection.py
  - [ ] Pxlabels.py
  - [ ] displayplot.py
  - [ ] queries.py
  - [ ] textorientation.py
  - [ ] textcombined.py
  - [ ] utils.py
  - [ ] vcshelp.py
  - [ ] Pylabels.py
  - [ ] Pdata.py
  - [ ] isofill.py
  - [ ] Pytickmarks.py
  - [ ] Pxtickmarks.py
  - [ ] taylor.py
  - [ ] xmldocs.py
  - [ ] vector.py
  - [ ] dv3d.py
  - [ ] marker.py
  - [ ] meshfill.py
  - [ ] Ptext.py
  - [ ] testtemplate.py
  - [ ] Pboxeslines.py
  - [ ] isoline.py
  - [ ] Pformat.py
  - [ ] line.py
  - [ ] Plegend.py
- [ ] Link to Aashish's documentation for data type references (cdms2 slabs, numpy arrays, etc.)
